<?xml version="1.0"?>
<robot name="five_dof_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Materials and colors -->
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <!-- Constants -->
  <xacro:property name="PI" value="3.14159265359" />
  
  <!-- Link dimensions -->
  <xacro:property name="base_radius" value="0.1" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="link_radius" value="0.04" />
  <xacro:property name="link1_length" value="0.2" />
  <xacro:property name="link2_length" value="0.2" />
  <xacro:property name="link3_length" value="0.15" />
  <xacro:property name="link4_length" value="0.15" />
  <xacro:property name="gripper_length" value="0.1" />
  
  <!-- Mass properties -->
  <xacro:property name="base_mass" value="1.0" />
  <xacro:property name="link1_mass" value="0.8" />
  <xacro:property name="link2_mass" value="0.8" />
  <xacro:property name="link3_mass" value="0.6" />
  <xacro:property name="link4_mass" value="0.6" />
  <xacro:property name="gripper_mass" value="0.3" />

  <!-- Inertia macro for cylindrical links -->
  <xacro:macro name="cylinder_inertia" params="mass radius length">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 ${length/2}" rpy="0 0 0" />
      <inertia 
        ixx="${mass * (3 * radius * radius + length * length) / 12}" 
        ixy="0.0" 
        ixz="0.0" 
        iyy="${mass * (3 * radius * radius + length * length) / 12}" 
        iyz="0.0" 
        izz="${mass * radius * radius / 2}" />
    </inertial>
  </xacro:macro>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
      <material name="grey" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia 
        ixx="${base_mass * (3 * base_radius * base_radius + base_height * base_height) / 12}" 
        ixy="0.0" 
        ixz="0.0" 
        iyy="${base_mass * (3 * base_radius * base_radius + base_height * base_height) / 12}" 
        iyz="0.0" 
        izz="${base_mass * base_radius * base_radius / 2}" />
    </inertial>
  </link>

  <!-- Joint 1: Base to Link 1 (Rotation around Z) -->
  <joint name="joint1" type="revolute">
    <parent link="base_link" />
    <child link="link1" />
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit lower="${-PI}" upper="${PI}" effort="100" velocity="1.0" />
  </joint>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link1_length}" />
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link1_length}" />
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia mass="${link1_mass}" radius="${link_radius}" length="${link1_length}" />
  </link>

  <!-- Joint 2: Link 1 to Link 2 (Rotation around Y) -->
  <joint name="joint2" type="revolute">
    <parent link="link1" />
    <child link="link2" />
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${-PI/2}" upper="${PI/2}" effort="100" velocity="1.0" />
  </joint>

  <!-- Link 2 -->
  <link name="link2">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link2_length}" />
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0" />
      <material name="green" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link2_length}" />
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia mass="${link2_mass}" radius="${link_radius}" length="${link2_length}" />
  </link>

  <!-- Joint 3: Link 2 to Link 3 (Rotation around Y) -->
  <joint name="joint3" type="revolute">
    <parent link="link2" />
    <child link="link3" />
    <origin xyz="0 0 ${link2_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${-PI/2}" upper="${PI/2}" effort="100" velocity="1.0" />
  </joint>

  <!-- Link 3 -->
  <link name="link3">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link3_length}" />
      </geometry>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0" />
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link3_length}" />
      </geometry>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia mass="${link3_mass}" radius="${link_radius}" length="${link3_length}" />
  </link>

  <!-- Joint 4: Link 3 to Link 4 (Rotation around Y) -->
  <joint name="joint4" type="revolute">
    <parent link="link3" />
    <child link="link4" />
    <origin xyz="0 0 ${link3_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${-PI/2}" upper="${PI/2}" effort="100" velocity="1.0" />
  </joint>

  <!-- Link 4 -->
  <link name="link4">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link4_length}" />
      </geometry>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0" />
      <material name="white" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link4_length}" />
      </geometry>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia mass="${link4_mass}" radius="${link_radius}" length="${link4_length}" />
  </link>

  <!-- Joint 5: Link 4 to Gripper (Rotation around Z) -->
  <joint name="joint5" type="revolute">
    <parent link="link4" />
    <child link="gripper" />
    <origin xyz="0 0 ${link4_length}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit lower="${-PI}" upper="${PI}" effort="100" velocity="1.0" />
  </joint>

  <!-- Gripper -->
  <link name="gripper">
    <visual>
      <geometry>
        <box size="${link_radius*2} ${link_radius*2} ${gripper_length}" />
      </geometry>
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <box size="${link_radius*2} ${link_radius*2} ${gripper_length}" />
      </geometry>
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0" />
    </collision>
    <inertial>
      <mass value="${gripper_mass}" />
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0" />
      <inertia 
        ixx="${gripper_mass * (link_radius*link_radius*4 + gripper_length*gripper_length) / 12}" 
        ixy="0.0" 
        ixz="0.0" 
        iyy="${gripper_mass * (link_radius*link_radius*4 + gripper_length*gripper_length) / 12}" 
        iyz="0.0" 
        izz="${gripper_mass * link_radius*link_radius*2 / 6}" />
    </inertial>
  </link>

  <!-- Gazebo specific colors -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="link1">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="link2">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="link3">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="link4">
    <material>Gazebo/White</material>
  </gazebo>
  <gazebo reference="gripper">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- Transmission elements for ROS 2 control -->
  <transmission name="trans_joint1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_joint2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_joint3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_joint4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_joint5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint5">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint5">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>